language: ruby
rvm:
    - 1.9.3
    - 2.0.0
    - 2.1.0

script: 'bundle exec rake'

matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_VERSION=3.7.4
  - rvm: 2.0.0
    env: PUPPET_VERSION=3.7.4
  - rvm: 2.0.0
    env: PUPPET_VERSION=3.7.4 FUTURE_PARSER="yes"
