sudo: false
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script: bundle exec rake validate lint spec
bundler_args: --without system_tests
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5"
notifications:
  email: false
